### ISSUE TITLE
failed to build LLB: failed to compute cache key: "/.git" not found: not found

### ISSUE THREAD

**Issue by weigeloveu** [PleasureTools/joyBox#17]
ERROR [stage-3 9/10] COPY .git ./.git                                                                          0.0s
[stage-3 9/10] COPY .git ./.git:
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: "/.git" not found: not found
i build it on win10 with this error

**Comment by judgegc** [comment]
Use `git clone` instead `Download zip`

**Comment by weigeloveu** [comment]
> Use `git clone` instead `Download zip`

thanks,still doesnt work with npm error
` => ERROR [deps 7/7] RUN npm i     && mv ./node_modules/@types/jsonstream ./node_modules/@types/JSONStream         1.9s
------
 > [deps 7/7] RUN npm i     && mv ./node_modules/@types/jsonstream ./node_modules/@types/JSONStream:
#12 1.853 npm ERR! code EISDIR
#12 1.854 npm ERR! syscall copyfile
#12 1.856 npm ERR! path /app/node_modules/chownr
#12 1.857 npm ERR! dest /app/node_modules/.chownr-cyv3QNXu
#12 1.859 npm ERR! errno -21
#12 1.863 npm ERR! EISDIR: illegal operation on a directory, copyfile '/app/node_modules/chownr' -> '/app/node_modules/.chownr-cyv3QNXu'
#12 1.875
#12 1.875 npm ERR! A complete log of this run can be found in:
#12 1.876 npm ERR!     /root/.npm/_logs/2020-12-07T05_06_26_841Z-debug.log`

**Comment by judgegc** [comment]
https://github.com/PleasureTools/joyBox/issues/18#issuecomment-754205002
