### ISSUE TITLE
now what ?

### ISSUE THREAD

**Issue by AkgunFatih** [PleasureTools/joyBox#4]
after running docker i open localhost:8080
what to do next ?
how can i add a recording ?

**Comment by AkgunFatih** [comment]
make it private if u dont care about community or if u are asocial

**Comment by judgegc** [comment]
Sry for that. But my english is trash, so I can't give you a sufficient answer :smirk:

**Comment by AkgunFatih** [comment]
@judgegc then write it in your own language
my friend name is google-translate
