### ISSUE TITLE
how could restart recording?

### ISSUE THREAD

**Issue by weigeloveu** [PleasureTools/joyBox#6]
thanks your joybox,it the best record app.
once stoped recording,if want to restart it need to remove from observable and readd it.
if could add more option,like "play" "pasue" "record" on observable list,like that
![SharedScreenshot](https://user-images.githubusercontent.com/19830500/75088460-66fd2200-5588-11ea-808e-eae6aa9026c4.jpg)
user will add lots of model like the screenshot,but most time is boring,just need record some wonderful moment.
with play button could preview if its the moment that want to record.

**Comment by judgegc** [comment]
You can restart here  `http://host:8080/recorder`. Recording will resume automatically in 10 sec
![unknown](https://user-images.githubusercontent.com/24261248/75093064-34065e80-5587-11ea-887f-c6cc9634ae8c.png)
Thanks for ideas. Maybe I'll implement the rest in the future
