### ISSUE TITLE
Can't delete Recorded Videos in Archive

### ISSUE THREAD

**Issue by Powerbock** [PleasureTools/joyBox#7]
Very nice piece of Software. But i can't delete any of my recorded videos in my Archive. After press on the the Trash Symbol, nothing, only a short Message "No Access". Can you please help me please?

A wish on my part for a future version might be the support of "camsoda".

Kind Regards
Ronald

UBUNTU 18.04 LTS Server

**Comment by AkgunFatih** [comment]
long press it
